// apps/kerolox/src/components/svelte/Earth.svelte
<!--
SPDX-FileCopyrightText: 2026 Helge Eichhorn <git@helgeeichhorn.de>

SPDX-License-Identifier: MPL-2.0
-->

<script lang="ts">
  import { T } from "@threlte/core";
  import { useTexture } from "@threlte/extras";
  const meanRadius = 6371;
</script>

<T.Mesh>
  <T.SphereGeometry args={[meanRadius, 64, 64]} />
  {#await useTexture("/assets/Earth-color.jpg") then texture}
    <T.MeshStandardMaterial map={texture} />
  {/await}
</T.Mesh>

// packages/lox-space-r3f/src/Earth.tsx
// SPDX-FileCopyrightText: 2026 Helge Eichhorn <git@helgeeichhorn.de>
//
// SPDX-License-Identifier: MPL-2.0

import { useLoader } from "@react-three/fiber";
import { Origin } from "@lox-space/wasm";
import { useMemo } from "react";
import { TextureLoader } from "three";

interface EarthProps {
  textureUrl?: string;
}

export function Earth({ textureUrl }: EarthProps) {
  const meanRadius = useMemo(() => {
    const earth = new Origin("Earth");
    return earth.mean_radius() / 1000; // m to km
  }, []);

  return (
    <mesh>
      <sphereGeometry args={[meanRadius, 64, 64]} />
      {textureUrl ? (
        <EarthTextured url={textureUrl} />
      ) : (
        <meshStandardMaterial color="#4488ff" />
      )}
    </mesh>
  );
}

function EarthTextured({ url }: { url: string }) {
  const texture = useLoader(TextureLoader, url);
  return <meshStandardMaterial map={texture} />;
}
